### PR TITLE
New Features added

### PR DESCRIPTION
**Pull request by billcccheng**
Thanks you for making this project. I really liked it!!

Features added
* Users do not have to get their session id(cookie) through chrome dev tool 
  *  Requests login and fetches the session id (users have to insert their password and username in `pref.json`)
* The userid of the story does not have to be manually inserted
* Refactored code and separated them into different function for better readability

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for contributing, I have a few comments:

* The two changes (session id and user id) should be configurable and optional
  * Session ID requires storing your password in the config file, which not everyone wants to do. Personally I prefer storing the session ID I retrieve manually than storing my instagram password in a file. 
  * User ID introduces a breaking change. This means people who do not pay attention at the commit history will see their script broken since configuration only requires the username, not userid. 
  * User ID also will not work well when users change username, which can and happens. At least with the old model you have one directory that stays the same even if the person changes their username
  * User ID fetching makes a call to a third party website, which is not desirable for many people. You also cannot guarantee the website will work in the future, which means things can and will break. 
  * User ID is not even cached, so you make N requests (N is number of people you follow) **EVERY TIME** the script is run. You could just cache the IDs in the sqlite database instead.
  
* You also introduced a new dependency (beautifulsoup4), which you didn't add in the requirements.txt

**Comment by billcccheng** [comment]
Thanks for the suggestions @hansenchris! I just pushed a new commit that uses the instagram api to get the userid. The rest I agree with you too and I will find time to also make those changes. Will make this backward compatible.

**Comment by ondrejsojka** [comment]
Firstly: Thank you **so much** for contributing. I can't describe how great it feels to have someone just contribute to something I started.

@hansenchris has already pointed out most of the things I wanted to point out, so I'll just expand on that.

Since there is really no reason to make a breaking change, we shouldn't make one. The script should let the user input the cookies directly, for example some people use 2FA on their IG account and this would be hard to get around.

Changing usernames are a problem I've seen firsthand after running this for over a year. People really do change their usernames very often. I'd suggest letting users specify both IDs and usernames in prefs.json and alert when an username is not found. This would keep everything nicely backwards-compatible.

**Comment by billcccheng** [comment]
Also, for the username and password stuff - I thought it was a better idea because a lot of users, especially users who are new to this area, are easily scared off seeing that you have to manually get your cookie from the developer tool. To make things worst, you have to escape all those special characters in the cookie when you paste it in. It's not really straight-forward.

**Comment by billcccheng** [comment]
@hoschiCZ  Just a quick followup question:  Do you think this is worth the work if I made it back-compatible or the project is good for now?  Again! Thanks for starting the project! :smiley:

**Comment by ondrejsojka** [comment]
It's definitely worth it to let the user specify their own headers and not put username and password into prefs.json. The current process is nowhere near straightforward, especially with the special characters nowadays.

However, I'm not sure about what do we do with the usernames/ids:

As of now, we save the media into folders named with the username. However, when people change their usernames, do we save the media into a new folder?

Also, how practical would it be to alert that a username is not found because it changed? Wouldn't it be easier for everybody if we defined IG users by id and not username? 

It is worth it to allow empty ids in prefs.json and make the script fill them in on first run. I'd suggest throwing away (from the PR draft) the usernames entry in prefs.json and just let it be `ids`. If this `ids` is a dict (or "object"), run as before, if this is a list, it's a list of usernames and the script should translate it to ids and usernames and update prefs.json.

**Comment by ondrejsojka** [comment]
@billcccheng Would you be willing to implement the changes proposed here or should I implement them?

**Comment by billcccheng** [comment]
Sorry, I am pretty swamped with recent work so I don't think I can squeeze in some time for this. I will close this pull request. Thanks!

**Comment by ondrejsojka** [comment]
I'm continuing work on this in the [billcccheng branch](https://github.com/hoschiCZ/instastories-backup/tree/billcccheng) in this repo.

**Comment by ondrejsojka** [comment]
:tada: I have just merged branch billcccheng to master! Thanks again! :tada:

**Pull request closed without merging**
